name=MultiTimerSAMD
version=1.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Hardware Timer Interrupt Library for SAMD21 and SAMD51
paragraph=Uses one or more 'Timer/Counters' (TC0..TC7 or TCC0..TCC4) with optional Channels (CH0..CH5) to generate one or more interrupts at various frequencies.
category=Timing
url=https://github.com/mumanchu/MultiTimerSAMD
architectures=samd
