name=MultiTimerSAMD
version=1.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Hardware Timer Interrupt Library for SAMD21 and SAMD51
paragraph=Uses one or more 'Timer/Counters' (TC0..TC7) and/or 'Timer/Counters for Control' (TCC0..TCC) with optional channels (CH1..CH5) to generate one or more interrupts at various frequencies.
category=Timing
url=https://github.com/mumanchu/MultiTimerSAMD
architectures=samd
